# For development
version: '3.9'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres:
